-- ケース管理 (リターン/未着) 用テーブル
CREATE TABLE IF NOT EXISTS case_records (
    id bigint generated by default as identity primary key,
    ebay_case_id text unique, -- eBay側のcaseId
    case_type text not null check (case_type in ('RETURN', 'INR')),
    status text not null, -- OPEN / CLOSED / ACTION_REQUIRED など
    account_id bigint not null references accounts(id) on delete cascade,
    order_id bigint references orders(id) on delete set null,
    buyer_id bigint references buyers(id) on delete set null,
    assignee_user_id bigint references users(id) on delete set null,
    reason text,
    requested_action text, -- REFUND / REPLACEMENT / RETURN_LABEL など
    expected_refund numeric(12,2),
    currency_code text,
    memo text,
    opened_at timestamp with time zone default now(),
    resolution_due_at timestamp with time zone,
    last_responded_at timestamp with time zone,
    return_tracking_number text,
    return_carrier text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS case_items (
    id bigint generated by default as identity primary key,
    case_id bigint not null references case_records(id) on delete cascade,
    order_line_item_id text references order_line_items(id) on delete set null,
    title text,
    quantity integer,
    refund_amount numeric(12,2),
    currency_code text
);

CREATE TABLE IF NOT EXISTS case_events (
    id bigint generated by default as identity primary key,
    case_id bigint not null references case_records(id) on delete cascade,
    event_type text not null, -- BUYER_MESSAGE / SELLER_RESPONSE / AUTO_UPDATE など
    payload jsonb,
    occurred_at timestamp with time zone default now(),
    created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS case_memos (
    id bigint generated by default as identity primary key,
    case_id bigint not null references case_records(id) on delete cascade,
    author_user_id bigint references users(id) on delete set null,
    body text not null,
    created_at timestamp with time zone default now()
);

CREATE INDEX IF NOT EXISTS case_records_status_idx ON case_records(status);
CREATE INDEX IF NOT EXISTS case_records_type_idx ON case_records(case_type);
CREATE INDEX IF NOT EXISTS case_records_resolution_due_idx ON case_records(resolution_due_at);
