-- Webhook settings per account
CREATE TABLE IF NOT EXISTS webhooks (
    id bigint generated by default as identity primary key,
    account_id bigint not null references accounts(id) on delete cascade,
    url text not null,
    event_type text not null,
    is_active boolean not null default true,
    created_at timestamp with time zone default now()
);

create index if not exists webhooks_account_id_idx on webhooks(account_id);
